### ISSUE TITLE
Panic when no positive values provided

### ISSUE THREAD

**Issue by 0x4c6565** [guptarohit/asciigraph#17]
When no positive floats are provided to `Plot()`, a panic is observed:

## Examples:
```
package main

import "github.com/guptarohit/asciigraph"

func main() {
	println(asciigraph.Plot([]float64{0}))
}
```
```
package main

import "github.com/guptarohit/asciigraph"

func main() {
	println(asciigraph.Plot([]float64{-1}))
}
```

## Result:
```
PS C:\Users\Lee\test> go run .\main.go
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/guptarohit/asciigraph.Plot(0xc00007df78, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/Lee/go/pkg/mod/github.com/guptarohit/asciigraph@v0.4.1/asciigraph.go:92 +0x13aa
main.main()
        C:/Users/Lee/test/main.go:6 +0x67
exit status 2
```

Line 92 is as follows:

```go
plot[rows-y0][config.Offset-1] = "┼" // first value
```

**Comment by mrtvfuencxozd** [comment]
Hi, 
In case you are still wondering,
I just has a similar issue (in fact my problem was that there was no range of value but a single repeated one).
Looking at it, I found that (for my case at least), this had been fixed in master.

Waiting for a new version, `go get github.com/guptarohit/asciigraph@f9506970428c1d46` did it for me.

Pascal

**Comment by 0x4c6565** [comment]
________________________________

**Comment by guptarohit** [comment]
@0x4c6565 this is fixed with the new release, please feel free to re-open if you still face the issue. :v:

**Comment by 0x4c6565** [comment]
Perfect, cheers @guptarohit !
