### ISSUE TITLE
How to install now that `go get` is deprecated

### ISSUE THREAD

**Issue by luckman212** [guptarohit/asciigraph#45]
This looks really neat. But I'm having trouble installing it. Anyone know of a workaround now that [`go get` is deprecated](https://go.dev/doc/go-get-install-deprecation)?

- macOS 13.4.1
- Go 1.20.5

#### go get
```
$ go get github.com/guptarohit/asciigraph
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```
#### go install
```
$ go install github.com/guptarohit/asciigraph@latest
package github.com/guptarohit/asciigraph is not a main package
```

**Comment by guptarohit** [comment]
Hi @luckman212,

Thanks for bringing it to my attention. I've updated [cli installation](https://github.com/guptarohit/asciigraph#cli-installation) instruction in README, this should work for installing cli.

Otherwise, if you wanted to have it as dependency in your Go application then there has to be `go.mod` file before running ` go get` command.
Command to initialise go module `go mod init <you module name>` .

Cheers!
