### ISSUE TITLE
Incorrect plot

### ISSUE THREAD

**Issue by mikesolem** [guptarohit/asciigraph#56]
First off, thanks for creating this.  It is very useful!

This data results in a graph with a flat line with all values at 0.00.

func main() {
	data := []float64{.2, .3, .2}
	graph := asciigraph.Plot(data)
	fmt.Println(graph)
}

**Comment by palash25** [comment]
@guptarohit if in case of a 0 height you override it with 1 this graph would plot correctly

**Comment by guptarohit** [comment]
Thanks @mikesolem for reporting the issue, this should be fixed with changes done in pull request [59](https://github.com/guptarohit/asciigraph/pull/59)

And thanks to @palash25 for sharing your insights over the issue. 💯

I've released new version [0.7.3](https://github.com/guptarohit/asciigraph/releases/tag/v0.7.3) 🎉, please give it a try.

✨
